/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:872e826e-dd07-4472-a5ca-7533eff3a516",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fz6cUccAB",
    "aws_user_pools_web_client_id": "2raklpe1083mcphus0fs90biop",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://wkxbauywinhp3moqk5devfvtx4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hjzj5qr5wjd5nplxieqswypmva",
    "aws_user_files_s3_bucket": "react8c873175be424f05a1c9dd52bd931582153617-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
